### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by KingFisherr** [KingFisherr/39575-Website#1]
- [X]  Info about home page (issue #1)
- [X] Links to eligibility details (issue #2)
- [X] Interactive pledge counter (issue #3)
